baseURL = 'https://blog.1407.org/'
languageCode = 'en-us'
title = 'FU-BAR - Fucked Up Beyond All Recognition'
theme = "ananke"
params:
  ananke_socials:
  - name: Mastodon
    url: https://mastodon.social/@RuiSeabra
  - name: twitter
    url: https://twitter.com/RuiSeabra
  - name: facebook
    url: https://www.facebook.com/rui.m.seabra/
